version: "3"
services:
  shifter-ui:
    container_name: shifter_ui_development
    domainname: shifter.local
    image: local.shifter.cloud/shifter-ui:latest
    environment:
      SHIFTER_SERVER_ENDPOINT: "https://dev.api.shifter.cloud/api/v1"
    ports:
      - 9090:8080
    links:
      - "shifter-server:shifter-server.local"
    networks:
      - shifter-network
  shifter-server:
    container_name: shifter_server_development
    domainname: shifter-server.local
    image: local.shifter.cloud/shifter:latest
    entrypoint: ["./shifter", "server"]
    ports:
      - 9091:8080
    networks:
      - shifter-network
networks:
  shifter-network:
